# Generated by Django 3.1.5 on 2021-02-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='asked_meal',
            field=models.ManyToManyField(null=True, to='canteen.FoodForMeal', verbose_name='已点的餐'),
        ),
    ]
