# Generated by Django 3.1.3 on 2021-04-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_auto_20210331_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to='foods', verbose_name='菜品图片'),
        ),
    ]
