# Generated by Django 3.1.5 on 2021-02-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_auto_20210210_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='asked_meal',
            field=models.ManyToManyField(blank=True, to='canteen.FoodForMeal', verbose_name='已点的餐'),
        ),
    ]
