# Generated by Django 3.1.5 on 2021-02-27 20:04

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_auto_20210210_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='canteen.meal', verbose_name='上次点餐的Meal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[200, 200], upload_to='foods', verbose_name='菜品图片'),
        ),
    ]
