# Generated by Django 3.2.4 on 2021-06-08 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=32, verbose_name='活动主题')),
                ('detail', models.TextField(verbose_name='活动描述')),
                ('date', models.DateField(verbose_name='活动日期')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='activity', verbose_name='活动图片')),
                ('description', models.TextField(verbose_name='图片描述')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity', verbose_name='关联的活动')),
            ],
        ),
    ]
